onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /TB_core_no_mem/UUT/clk
add wave -noupdate /TB_core_no_mem/UUT/RST
add wave -noupdate /TB_core_no_mem/UUT/intr
add wave -noupdate /TB_core_no_mem/UUT/iobus_in
add wave -noupdate /TB_core_no_mem/UUT/iobus_out
add wave -noupdate /TB_core_no_mem/UUT/iobus_addr
add wave -noupdate /TB_core_no_mem/UUT/iobus_wr
add wave -noupdate /TB_core_no_mem/UUT/I_immed
add wave -noupdate /TB_core_no_mem/UUT/S_immed
add wave -noupdate /TB_core_no_mem/UUT/U_immed
add wave -noupdate /TB_core_no_mem/UUT/B_immed
add wave -noupdate /TB_core_no_mem/UUT/J_immed
add wave -noupdate /TB_core_no_mem/UUT/IR
add wave -noupdate /TB_core_no_mem/UUT/regWrite
add wave -noupdate /TB_core_no_mem/UUT/memWrite
add wave -noupdate /TB_core_no_mem/UUT/mem_op
add wave -noupdate /TB_core_no_mem/UUT/memRead
add wave -noupdate /TB_core_no_mem/UUT/memRead2
add wave -noupdate /TB_core_no_mem/UUT/pc_source
add wave -noupdate /TB_core_no_mem/UUT/pc_sel
add wave -noupdate /TB_core_no_mem/UUT/rf_wr_sel
add wave -noupdate /TB_core_no_mem/UUT/alu_fun
add wave -noupdate /TB_core_no_mem/UUT/de_inst
add wave -noupdate /TB_core_no_mem/UUT/ex_inst
add wave -noupdate /TB_core_no_mem/UUT/mem_inst
add wave -noupdate /TB_core_no_mem/UUT/wb_inst
add wave -noupdate /TB_core_no_mem/UUT/pc
add wave -noupdate /TB_core_no_mem/UUT/pc_value
add wave -noupdate /TB_core_no_mem/UUT/jalr_pc
add wave -noupdate /TB_core_no_mem/UUT/branch_pc
add wave -noupdate /TB_core_no_mem/UUT/jump_pc
add wave -noupdate /TB_core_no_mem/UUT/pcWrite
add wave -noupdate /TB_core_no_mem/UUT/jal_pc
add wave -noupdate /TB_core_no_mem/UUT/mem_data
add wave -noupdate /TB_core_no_mem/UUT/opcode
add wave -noupdate /TB_core_no_mem/UUT/OPCODE
add wave -noupdate /TB_core_no_mem/UUT/rfIn
add wave -noupdate /TB_core_no_mem/UUT/rs1
add wave -noupdate /TB_core_no_mem/UUT/br_lt
add wave -noupdate /TB_core_no_mem/UUT/br_eq
add wave -noupdate /TB_core_no_mem/UUT/br_ltu
add wave -noupdate /TB_core_no_mem/UUT/opA_sel
add wave -noupdate /TB_core_no_mem/UUT/opB_sel
add wave -noupdate /TB_core_no_mem/UUT/aluAin
add wave -noupdate /TB_core_no_mem/UUT/aluBin
add wave -noupdate /TB_core_no_mem/UUT/rs2
add wave -noupdate /TB_core_no_mem/UUT/mem_rs2
add wave -noupdate /TB_core_no_mem/UUT/mem_aluRes
add wave -noupdate /TB_core_no_mem/UUT/opA_forwarded
add wave -noupdate /TB_core_no_mem/UUT/opB_forwarded
add wave -noupdate /TB_core_no_mem/UUT/alu_result
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
quietly wave cursor active 0
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1 ns}
